# Railway configuration for Props deployment
# Updated: Profile page with balance management
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
NODE_ENV = "production"
NODE_VERSION = "18.x"
HOST = "0.0.0.0"

[nixpacks]
nixPkgs = ["nodejs", "postgresql"] 