# Railway configuration for Props deployment
# Updated: Global search bar and balance display
[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npx prisma generate && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 10

[env]
PORT = "8080"
NODE_ENV = "production"
NODE_VERSION = "18.x"
HOST = "0.0.0.0"

[nixpacks]
nixPkgs = ["nodejs", "postgresql"] 