# Railway configuration for Props deployment
[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 10

[env]
PORT = "8080"
NODE_ENV = "production" 